import { logout } from "@/features/auth/actions";
import { createClient } from "@/utils/supabase/server";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data, error } = await (await createClient()).auth.getUser();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="flex flex-row items-center gap-10">
          <h1 className="text-2xl font-bold">{error ? "Anonymous" : data.user.email}</h1>
          {error ? (
            <Link href="/login" className=" text-sm bg-blue-500 p-1 rounded-sm">
              Login
            </Link>
          ) : (
            <form action={logout}>
              <button className="text-sm bg-blue-500 p-1 rounded-sm">Logout</button>
            </form>
          )}
        </header>
        <details>
          <summary>Auth 정보</summary>
          <pre className="border rounded-sm">{JSON.stringify(data, null, 2)}</pre>
          <pre className="border rounded-sm">{JSON.stringify(error, null, 2)}</pre>
        </details>
        <hr className="my-3" />
        <main>{children}</main>
      </body>
    </html>
  );
}
